image: docker:latest
services:
  - docker:dind

stages:
  - testing

unit-testing:
  stage: testing
  image: golang:1.16-alpine
  script:
    - apk update && apk add --no-cache git build-base
    - export GO111MODULE=on
    - go test -cover -v ./...
  except:
    - master
    