image: golang:1.12

before_script:
    - mkdir -p /go/src/gitlab.com/auth-service
    - export GOPATH=$HOME/go

stages:
    - test

test:
    stage: test
    script:
        - cd $GOPATH/src/gitlab.com/auth-service
        - make test
    