image: golang:1.12

before_script:
    - mkdir -p /go/src/gitlab.com/auth-service

stages:
    - test

test:
    stage: test
    script:
        - cd /go/src/gitlab.com/auth-service
        - go test ./... -cover
    